SUPABASE_URL = "https://dhifmugekydgcxkfilru.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoaWZtdWdla3lkZ2N4a2ZpbHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODU0OTEsImV4cCI6MjA3MDY2MTQ5MX0.b2SC5vTOLVkG26bb1_z00HmkFhiatvl52D3Uc1RYAmk"
